package com.modeldoctor.domain;

public enum ExperimentType {
    FEATURE_ABLATION,
    FEATURE_TRANSFORMATION,
    MISSING_VALUE_STRESS,
    THRESHOLD_COUNTERFACTUAL,
    CALIBRATION_COUNTERFACTUAL,
    SUBGROUP_COUNTERFACTUAL
}
