package com.modeldoctor.domain;

public enum RemediationType {
    DATA_QUALITY_REPAIR,
    FEATURE_ENGINEERING_REVIEW,
    FEATURE_REMOVAL_REVIEW,
    DATA_LEAKAGE_REVIEW,
    DISTRIBUTION_SHIFT_INVESTIGATION,
    CALIBRATION_REVIEW,
    THRESHOLD_REVIEW,
    CLASS_IMBALANCE_REVIEW,
    FAIRNESS_REVIEW,
    ROBUSTNESS_REVIEW,
    MODEL_COMPLEXITY_REVIEW,
    ERROR_SEGMENT_REVIEW,
    DATA_COLLECTION_REVIEW,
    EVALUATION_DATA_REVIEW
}
