spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:modeldoctor_db}}
    username: ${POSTGRES_USER:modeldoctor_admin}
    password: ${POSTGRES_PASSWORD:modeldoctor_secret_password_change_me}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
