import {
  CalibrationBin,
  DiagnosticRunRecord,
  DistributionBin,
  FeatureEdge,
  FeatureNode,
  LogEntry,
  ModelDiagnosticSummary,
} from "@/types/diagnostics";

/**
 * Technical test fixtures for Model Doctor diagnostic workstation.
 * Data is explicitly flagged as mock/demo data for initial visual validation.
 */

export const MODEL_SUMMARY: ModelDiagnosticSummary = {
  modelId: "fraud_classifier_v17",
  modelVersion: "17.4.2",
  framework: "XGBoost 2.0.3",
  taskType: "Binary Classification",
  datasetName: "production_2026_09",
  sampleCount: 250000,
  featureCount: 47,
  runId: "#0042",
  healthScore: 73,
  criticalFindingsCount: 3,
  warningsCount: 5,
  observationsCount: 14,
  maxPsiDrift: 0.312,
  maxMutualInfoLeakage: 0.941,
  expectedCalibrationError: 0.084,
  brierScore: 0.068,
  disparateImpactRatio: 0.771,
  gaussianJitterFlipRate: 0.148,
  isMockData: true,
};

export const FEATURE_NODES: FeatureNode[] = [
  {
    id: "f_01",
    name: "transaction_id_hash",
    dataType: "identifier",
    missingRate: 0.0,
    mutualInfoTarget: 0.941,
    correlationTarget: 0.962,
    ksPValue: 0.98,
    psiValue: 0.012,
    shapImportance: 0.421,
    outlierFraction: 0.0,
    severity: "CRITICAL",
    anomalyType: "Direct Target Proxy Leakage",
    rootCause:
      "High mutual information (MI = 0.941). Hash generation logic inadvertently encodes fraudulent label flags from the source OLTP table.",
    recommendation:
      "Drop 'transaction_id_hash' from feature store ingestion pipeline before retraining.",
    x: 480,
    y: 160,
  },
  {
    id: "f_02",
    name: "user_velocity_6h",
    dataType: "int64",
    missingRate: 0.0,
    mutualInfoTarget: 0.412,
    correlationTarget: 0.384,
    ksPValue: 0.0001,
    psiValue: 0.312,
    shapImportance: 0.184,
    outlierFraction: 0.038,
    severity: "CRITICAL",
    anomalyType: "Severe Covariate Shift (PSI >= 0.25)",
    rootCause:
      "Population Stability Index is 0.312. Upper quantile distribution shifted post-deployment due to automated bot traffic increase.",
    recommendation:
      "Re-bin upper distribution tail (> 12 transactions/6h) or apply robust quantile clipping.",
    x: 240,
    y: 190,
  },
  {
    id: "f_03",
    name: "billing_zip_code",
    dataType: "categorical",
    missingRate: 0.0218,
    mutualInfoTarget: 0.142,
    correlationTarget: 0.082,
    ksPValue: 0.024,
    psiValue: 0.142,
    shapImportance: 0.064,
    outlierFraction: 0.0,
    severity: "WARNING",
    anomalyType: "High Unseen Category Rate & Missingness",
    rootCause:
      "Missing rate increased to 2.18% in production. 18.4% of observed zip codes were not present in training vocabulary.",
    recommendation:
      "Impute missing zip codes with explicit 'UNKNOWN' category and apply frequency encoding.",
    x: 160,
    y: 340,
  },
  {
    id: "f_04",
    name: "device_trust_score",
    dataType: "float64",
    missingRate: 0.042,
    mutualInfoTarget: 0.482,
    correlationTarget: -0.512,
    ksPValue: 0.008,
    psiValue: 0.184,
    shapImportance: 0.218,
    outlierFraction: 0.012,
    severity: "WARNING",
    anomalyType: "Moderate Distribution Drift & Missingness",
    rootCause:
      "SDK integration bug causing 4.2% null entries on mobile iOS client versions.",
    recommendation:
      "Verify client SDK telemetry pipeline and ensure median fallback value is applied.",
    x: 360,
    y: 380,
  },
  {
    id: "f_05",
    name: "amount_usd",
    dataType: "float64",
    missingRate: 0.0,
    mutualInfoTarget: 0.318,
    correlationTarget: 0.294,
    ksPValue: 0.34,
    psiValue: 0.042,
    shapImportance: 0.284,
    outlierFraction: 0.0142,
    severity: "NOMINAL",
    anomalyType: "None",
    rootCause: "Stable across baseline and production sets.",
    recommendation: "Maintain current feature transformation.",
    x: 320,
    y: 220,
  },
  {
    id: "f_06",
    name: "is_foreign_ip",
    dataType: "categorical",
    missingRate: 0.0,
    mutualInfoTarget: 0.218,
    correlationTarget: 0.312,
    ksPValue: 0.41,
    psiValue: 0.038,
    shapImportance: 0.092,
    outlierFraction: 0.0,
    severity: "WARNING",
    anomalyType: "Disparate Impact Violation (Ratio = 0.771)",
    rootCause:
      "Favorable classification rate for subgroup [cross_border_travelers] is 0.771x baseline, violating 80% parity threshold.",
    recommendation:
      "Apply post-hoc threshold adjustment across regional traffic slices.",
    x: 600,
    y: 290,
  },
  {
    id: "f_07",
    name: "auth_attempts_24h",
    dataType: "int64",
    missingRate: 0.0,
    mutualInfoTarget: 0.284,
    correlationTarget: 0.348,
    ksPValue: 0.12,
    psiValue: 0.071,
    shapImportance: 0.114,
    outlierFraction: 0.008,
    severity: "WARNING",
    anomalyType: "Adversarial Jitter Sensitivity (14.8% Flip)",
    rootCause:
      "Decision boundary exhibits high gradient sensitivity when integer count is perturbed by +/- 1 attempt.",
    recommendation:
      "Smooth boundary with label regularization or feature binning.",
    x: 460,
    y: 430,
  },
  {
    id: "f_08",
    name: "merchant_category_code",
    dataType: "categorical",
    missingRate: 0.001,
    mutualInfoTarget: 0.184,
    correlationTarget: 0.124,
    ksPValue: 0.52,
    psiValue: 0.024,
    shapImportance: 0.081,
    outlierFraction: 0.0,
    severity: "NOMINAL",
    anomalyType: "None",
    x: 580,
    y: 420,
  },
  {
    id: "f_09",
    name: "card_age_days",
    dataType: "float64",
    missingRate: 0.0,
    mutualInfoTarget: 0.142,
    correlationTarget: -0.198,
    ksPValue: 0.61,
    psiValue: 0.018,
    shapImportance: 0.072,
    outlierFraction: 0.002,
    severity: "NOMINAL",
    anomalyType: "None",
    x: 180,
    y: 260,
  },
  {
    id: "f_10",
    name: "ip_risk_score",
    dataType: "float64",
    missingRate: 0.004,
    mutualInfoTarget: 0.342,
    correlationTarget: 0.412,
    ksPValue: 0.18,
    psiValue: 0.062,
    shapImportance: 0.162,
    outlierFraction: 0.009,
    severity: "NOMINAL",
    anomalyType: "None",
    x: 410,
    y: 280,
  },
];

export const FEATURE_EDGES: FeatureEdge[] = [
  { source: "f_01", target: "f_05", weight: 0.88, isAnomaly: true },
  { source: "f_01", target: "f_06", weight: 0.76, isAnomaly: true },
  { source: "f_02", target: "f_07", weight: 0.68, isAnomaly: true },
  { source: "f_02", target: "f_05", weight: 0.44, isAnomaly: false },
  { source: "f_03", target: "f_06", weight: 0.38, isAnomaly: false },
  { source: "f_04", target: "f_10", weight: 0.72, isAnomaly: false },
  { source: "f_05", target: "f_08", weight: 0.31, isAnomaly: false },
  { source: "f_07", target: "f_10", weight: 0.54, isAnomaly: false },
  { source: "f_09", target: "f_02", weight: 0.28, isAnomaly: false },
];

export const DISTRIBUTION_BINS: DistributionBin[] = [
  { binIndex: 0, binRange: "[0 - 1]", baselineDensity: 0.482, currentDensity: 0.312, psiDelta: 0.074 },
  { binIndex: 1, binRange: "[2 - 3]", baselineDensity: 0.241, currentDensity: 0.218, psiDelta: 0.002 },
  { binIndex: 2, binRange: "[4 - 5]", baselineDensity: 0.134, currentDensity: 0.148, psiDelta: 0.001 },
  { binIndex: 3, binRange: "[6 - 7]", baselineDensity: 0.072, currentDensity: 0.112, psiDelta: 0.018 },
  { binIndex: 4, binRange: "[8 - 9]", baselineDensity: 0.038, currentDensity: 0.084, psiDelta: 0.036 },
  { binIndex: 5, binRange: "[10 - 12]", baselineDensity: 0.019, currentDensity: 0.062, psiDelta: 0.051 },
  { binIndex: 6, binRange: "[13 - 15]", baselineDensity: 0.009, currentDensity: 0.038, psiDelta: 0.042 },
  { binIndex: 7, binRange: "[16 - 20]", baselineDensity: 0.003, currentDensity: 0.018, psiDelta: 0.027 },
  { binIndex: 8, binRange: "[21 - 30]", baselineDensity: 0.001, currentDensity: 0.006, psiDelta: 0.019 },
  { binIndex: 9, binRange: "[> 30]", baselineDensity: 0.001, currentDensity: 0.002, psiDelta: 0.042 },
];

export const CALIBRATION_BINS: CalibrationBin[] = [
  { binIndex: 0, predictedProbability: 0.05, observedFrequency: 0.02, sampleCount: 142000 },
  { binIndex: 1, predictedProbability: 0.15, observedFrequency: 0.09, sampleCount: 48000 },
  { binIndex: 2, predictedProbability: 0.25, observedFrequency: 0.18, sampleCount: 22000 },
  { binIndex: 3, predictedProbability: 0.35, observedFrequency: 0.28, sampleCount: 14000 },
  { binIndex: 4, predictedProbability: 0.45, observedFrequency: 0.41, sampleCount: 8500 },
  { binIndex: 5, predictedProbability: 0.55, observedFrequency: 0.54, sampleCount: 5200 },
  { binIndex: 6, predictedProbability: 0.65, observedFrequency: 0.69, sampleCount: 3900 },
  { binIndex: 7, predictedProbability: 0.75, observedFrequency: 0.82, sampleCount: 2800 },
  { binIndex: 8, predictedProbability: 0.85, observedFrequency: 0.91, sampleCount: 2100 },
  { binIndex: 9, predictedProbability: 0.95, observedFrequency: 0.98, sampleCount: 1500 },
];

export const EVENT_LOGS: LogEntry[] = [
  {
    id: "log_01",
    timestamp: "15:14:02.184",
    level: "CRIT",
    module: "LEAKAGE_ENGINE",
    message: "VIOLATION: Mutual information = 0.941 on feature 'transaction_id_hash' against target 'is_fraud'. Threshold: 0.850.",
  },
  {
    id: "log_02",
    timestamp: "15:13:58.912",
    level: "CRIT",
    module: "DRIFT_ENGINE",
    message: "ALERT: KS two-sample test rejected null hypothesis on 'user_velocity_6h' (D=0.284, p=0.0001, PSI=0.312).",
  },
  {
    id: "log_03",
    timestamp: "15:13:51.440",
    level: "WARN",
    module: "FAIRNESS_ENGINE",
    message: "Disparate impact ratio = 0.771 on protected attribute 'is_foreign_ip'. Violates 0.800 legal threshold.",
  },
  {
    id: "log_04",
    timestamp: "15:13:44.208",
    level: "WARN",
    module: "ROBUSTNESS_ENGINE",
    message: "Gaussian noise injection (std=0.05) caused 14.8% classification flip on feature 'auth_attempts_24h'.",
  },
  {
    id: "log_05",
    timestamp: "15:13:38.102",
    level: "WARN",
    module: "CALIBRATION_ENGINE",
    message: "Expected Calibration Error (ECE) = 0.084 across 10 probability deciles. Overconfidence in range [0.0 - 0.2].",
  },
  {
    id: "log_06",
    timestamp: "15:13:25.019",
    level: "EVAL",
    module: "DATA_QUALITY",
    message: "Missing value audit completed across 47 columns. 2 columns flagged with null rates > 1.0%.",
  },
  {
    id: "log_07",
    timestamp: "15:13:12.800",
    level: "INFO",
    module: "ORCHESTRATOR",
    message: "Dataset partition 'production_2026_09' (250,000 rows, 47 cols) ingested from MinIO store in 482ms.",
  },
];

export const DIAGNOSTIC_RUNS: DiagnosticRunRecord[] = [
  {
    id: "run_0042",
    runNumber: "#0042",
    modelName: "fraud_classifier_v17",
    modelVersion: "17.4.2",
    datasetName: "production_2026_09",
    healthScore: 73,
    criticalCount: 3,
    warningCount: 5,
    sampleCount: 250000,
    durationMs: 1420,
    timestamp: "2026-10-06 15:14:02",
    status: "FAIL",
  },
  {
    id: "run_0041",
    runNumber: "#0041",
    modelName: "fraud_classifier_v16",
    modelVersion: "16.1.0",
    datasetName: "validation_golden_2026_08",
    healthScore: 89,
    criticalCount: 0,
    warningCount: 2,
    sampleCount: 180000,
    durationMs: 1120,
    timestamp: "2026-10-05 18:22:40",
    status: "WARN",
  },
  {
    id: "run_0040",
    runNumber: "#0040",
    modelName: "credit_risk_lgbm_v04",
    modelVersion: "4.0.1",
    datasetName: "credit_eval_q3",
    healthScore: 82,
    criticalCount: 1,
    warningCount: 4,
    sampleCount: 95000,
    durationMs: 890,
    timestamp: "2026-10-04 11:05:18",
    status: "WARN",
  },
  {
    id: "run_0039",
    runNumber: "#0039",
    modelName: "churn_detector_mlp",
    modelVersion: "2.3.0",
    datasetName: "churn_stream_sample",
    healthScore: 94,
    criticalCount: 0,
    warningCount: 1,
    sampleCount: 50000,
    durationMs: 2410,
    timestamp: "2026-10-02 09:40:11",
    status: "PASS",
  },
];
